# Form implementation generated from reading ui file 'ChiTietHoaDon.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import Dataconnection
from PyQt6.QtGui import QStandardItemModel, QStandardItem

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChiTietHoaDon(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 358)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(740, 10, 201, 251))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        # self.btnSua = QtWidgets.QPushButton(parent=self.groupBox)
        # self.btnSua.setGeometry(QtCore.QRect(40, 30, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        # self.btnSua.setFont(font)
        # self.btnSua.setObjectName("btnSua")
        # self.btnXoa = QtWidgets.QPushButton(parent=self.groupBox)
        # self.btnXoa.setGeometry(QtCore.QRect(40, 100, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        # self.btnXoa.setFont(font)
        # self.btnXoa.setObjectName("btnXoa")
        self.btnQuayLai = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnQuayLai.setGeometry(QtCore.QRect(40, 30, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnQuayLai.setFont(font)
        self.btnQuayLai.setObjectName("btnQuayLai")
        self.btnQuayLai.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.tableViewChiTietHoaDon = QtWidgets.QTableView(parent=Dialog)
        self.tableViewChiTietHoaDon.setGeometry(QtCore.QRect(20, 70, 691, 181))
        self.tableViewChiTietHoaDon.setObjectName("tableViewChiTietHoaDon")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(480, 30, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        # self.txtSL = QtWidgets.QTextEdit(parent=Dialog)
        # self.txtSL.setGeometry(QtCore.QRect(550, 30, 161, 21))
        # self.txtSL.setObjectName("txtSL")
        self.btnTimKiem = QtWidgets.QPushButton(parent=Dialog)
        self.btnTimKiem.setGeometry(QtCore.QRect(380, 30, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnTimKiem.setFont(font)
        self.btnTimKiem.setObjectName("btnTimKiem")
        self.btnTimKiem.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.txtTimKiemMa = QtWidgets.QTextEdit(parent=Dialog)
        self.txtTimKiemMa.setGeometry(QtCore.QRect(200, 30, 161, 21))
        self.txtTimKiemMa.setObjectName("txtTimKiemMa")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # #############
        self.btnTimKiem.clicked.connect(self.searchChiTietHoaDon)
        # self.tableViewChiTietHoaDon.clicked.connect(self.table_clicked)
        # self.btnSua.clicked.connect(self.SuaSoLuong)
        # self.btnXoa.clicked.connect(self.Xoa)
        self.btnQuayLai.clicked.connect(Dialog.close)
        # 
        self.ChiTiet_table()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Quản Lý Chi Tiết Hóa Đơn"))
        # self.btnSua.setText(_translate("Dialog", "Sửa"))
        # self.btnXoa.setText(_translate("Dialog", "Xóa"))
        self.btnQuayLai.setText(_translate("Dialog", "Quay Lại"))
        self.label.setText(_translate("Dialog", "Tìm Kiếm Theo Mã Hóa Đơn"))
        # self.label_2.setText(_translate("Dialog", "Số Lượng"))
        self.btnTimKiem.setText(_translate("Dialog", "Tìm Kiếm"))
        
    def ChiTiet_table(self):
        self.ChiTiet = QStandardItemModel()
        self.tableViewChiTietHoaDon.setModel(self.ChiTiet)
        header = self.tableViewChiTietHoaDon.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)


    def searchChiTietHoaDon(self):
        # Get the MaSP from the search text box
        ma_hd = self.txtTimKiemMa.toPlainText().strip()
        connection = Dataconnection.connectdatabase()
        if connection:
            cursor = connection.cursor()
            query = "SELECT TenSP,SoLuong,GiaBan FROM ChiTietHoaDon WHERE MaHD = %s"
            cursor.execute(query, (ma_hd,))
            results = cursor.fetchall()
            cursor.close()
            connection.close()

            # Update the model with the results
            self.ChiTiet.clear()
            if results:
                headers = ['TenSP', 'SoLuong', 'GiaBan']   
                self.ChiTiet.setHorizontalHeaderLabels(headers)

                for row in results:
                    items = [QtGui.QStandardItem(str(field)) for field in row]
                    self.ChiTiet.appendRow(items)
            else:
                self.ChiTiet.setHorizontalHeaderLabels(['< Không có chi tiết hóa đơn nào >'])
                self.tableViewChiTietHoaDon.resizeColumnsToContents()        
    # def table_clicked(self, index):
    #     row = index.row()
    #     self.txtSL.setText(self.ChiTiet.item(row, 4).text())
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_ChiTietHoaDon()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
