# Form implementation generated from reading ui file 'NhaCC.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import Dataconnection
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox, QTableView, QLineEdit, QPushButton


class Ui_NhaCungCap(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1526, 883)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1501, 261))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 30, 121, 16))
        self.label.setObjectName("label")
        self.txtMaNCC = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtMaNCC.setGeometry(QtCore.QRect(230, 20, 161, 22))
        self.txtMaNCC.setObjectName("txtMaNCC")
        self.txtTenNCC = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtTenNCC.setGeometry(QtCore.QRect(230, 70, 161, 22))
        self.txtTenNCC.setObjectName("txtTenNCC")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 121, 16))
        self.label_2.setObjectName("label_2")
        self.txtDiaChi = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtDiaChi.setGeometry(QtCore.QRect(230, 120, 161, 22))
        self.txtDiaChi.setObjectName("txtDiaChi")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 131, 16))
        self.label_3.setObjectName("label_3")
        self.txtSDT = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtSDT.setGeometry(QtCore.QRect(230, 160, 161, 22))
        self.txtSDT.setObjectName("txtSDT")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 111, 16))
        self.label_4.setObjectName("label_4")
        self.txtEmail = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txtEmail.setGeometry(QtCore.QRect(230, 200, 161, 22))
        self.txtEmail.setObjectName("txtEmail")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(40, 210, 55, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 10, 1011, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnThem = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnThem.setGeometry(QtCore.QRect(20, 30, 201, 61))
        self.btnThem.setStyleSheet("background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnThem.setObjectName("btnThem")
        self.btnSua = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnSua.setGeometry(QtCore.QRect(280, 30, 201, 61))
        self.btnSua.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(85, 85, 127);")
        self.btnSua.setObjectName("btnSua")
        self.btnXoa = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnXoa.setGeometry(QtCore.QRect(540, 30, 201, 61))
        self.btnXoa.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(85, 85, 127);")
        self.btnXoa.setObjectName("btnXoa")
        self.btnLamMoi = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnLamMoi.setGeometry(QtCore.QRect(800, 30, 201, 61))
        self.btnLamMoi.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(85, 85, 127);\n"
"")
        self.btnLamMoi.setObjectName("btnLamMoi")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 150, 1011, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.txtTimKiem = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.txtTimKiem.setGeometry(QtCore.QRect(240, 30, 181, 31))
        self.txtTimKiem.setObjectName("txtTimKiem")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 221, 16))
        self.label_11.setObjectName("label_11")
        self.btnTimKiem = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.btnTimKiem.setGeometry(QtCore.QRect(480, 30, 121, 31))
        self.btnTimKiem.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(85, 85, 127);\n"
"")
        self.btnTimKiem.setObjectName("btnTimKiem")
        self.tableView_NhaCungCap = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_NhaCungCap.setGeometry(QtCore.QRect(10, 300, 1501, 521))
        self.tableView_NhaCungCap.setStyleSheet("font: 10pt \"Microsoft YaHei UI\";")
        self.tableView_NhaCungCap.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.tableView_NhaCungCap.setObjectName("tableView_NhaCungCap")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1526, 21))
        self.menubar.setObjectName("menubar")
        self.menuManager = QtWidgets.QMenu(parent=self.menubar)
        self.menuManager.setObjectName("menuManager")
        self.menuSetting = QtWidgets.QMenu(parent=self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Home = QtGui.QAction(parent=MainWindow)
        self.action_Home.setObjectName("action_Home")
        self.actionSanPham = QtGui.QAction(parent=MainWindow)
        self.actionSanPham.setObjectName("actionSanPham")
        self.actionBanHang = QtGui.QAction(parent=MainWindow)
        self.actionBanHang.setObjectName("actionBanHang")
        self.actionNhanVien = QtGui.QAction(parent=MainWindow)
        self.actionNhanVien.setObjectName("actionNhanVien")
        self.actionNhaCungCap = QtGui.QAction(parent=MainWindow)
        self.actionNhaCungCap.setObjectName("actionNhaCungCap")
        self.actionThongKe = QtGui.QAction(parent=MainWindow)
        self.actionThongKe.setObjectName("actionThongKe")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLogout = QtGui.QAction(parent=MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionHoTro = QtGui.QAction(parent=MainWindow)
        self.actionHoTro.setObjectName("actionHoTro")
        self.menuManager.addAction(self.action_Home)
        self.menuManager.addAction(self.actionSanPham)
        self.menuManager.addAction(self.actionBanHang)
        self.menuManager.addAction(self.actionNhanVien)
        self.menuManager.addAction(self.actionNhaCungCap)
        self.menuManager.addAction(self.actionThongKe)
        self.menuSetting.addAction(self.actionExit)
        self.menuSetting.addAction(self.actionLogout)
        self.menuSetting.addAction(self.actionHoTro)
        self.menubar.addAction(self.menuManager.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # Khởi tạo model cho QTableView
        self.model = QtGui.QStandardItemModel()
         # Kết nối tới các nút chức năng
        self.btnThem.clicked.connect(self.themNhaCungCap)
        self.btnSua.clicked.connect(self.suaNhaCungCap)
        self.btnXoa.clicked.connect(self.xoaNhaCungCap)
        self.btnLamMoi.clicked.connect(self.lamMoi)
        self.btnTimKiem.clicked.connect(self.timKiemNhaCungCap)
        
        # Load dữ liệu lên bảng khi khởi động
        self.loadTableData()
        
        # Kết nối sự kiện click vào bảng
        self.tableView_NhaCungCap.clicked.connect(self.rowClicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Mã nhà cung cấp"))
        self.label_2.setText(_translate("MainWindow", "Tên nhà cung cấp"))
        self.label_3.setText(_translate("MainWindow", "Địa chỉ"))
        self.label_4.setText(_translate("MainWindow", "Điện Thoai"))
        self.label_5.setText(_translate("MainWindow", "Email"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Chức năng"))
        self.btnThem.setText(_translate("MainWindow", "THÊM MỚI NHÀ CUNG CẤP"))
        self.btnSua.setText(_translate("MainWindow", "SỬA THÔNG TIN"))
        self.btnXoa.setText(_translate("MainWindow", "XÓA "))
        self.btnLamMoi.setText(_translate("MainWindow", "LÀM MỚI"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tìm Kiếm"))
        self.label_11.setText(_translate("MainWindow", "Nhập Tên Nhà Cung Cấp Muốn Tìm"))
        self.btnTimKiem.setText(_translate("MainWindow", "Tìm Kiếm"))
        self.menuManager.setTitle(_translate("MainWindow", "Manager"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.action_Home.setText(_translate("MainWindow", " Home"))
        self.actionSanPham.setText(_translate("MainWindow", "SanPham"))
        self.actionBanHang.setText(_translate("MainWindow", "BanHang"))
        self.actionNhanVien.setText(_translate("MainWindow", "NhanVien"))
        self.actionNhaCungCap.setText(_translate("MainWindow", "NhaCungCap"))
        self.actionThongKe.setText(_translate("MainWindow", "ThongKe"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionHoTro.setText(_translate("MainWindow", "HoTro"))
        
    def loadTableData(self):
        try:
            conn = Dataconnection.connectdatabase()
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM NhaCungCap")
            rows = cursor.fetchall()

            self.model.clear()
            self.model.setColumnCount(5)
            self.model.setHorizontalHeaderLabels(["Mã NCC", "Tên NCC", "Địa Chỉ", "Điện Thoại", "Email"])
            
            

            for row_number, row_data in enumerate(rows):
                for column_number, data in enumerate(row_data):
                    item = QtGui.QStandardItem(str(data))
                    self.model.setItem(row_number, column_number, item)

            self.tableView_NhaCungCap.setModel(self.model)
            header = self.tableView_NhaCungCap.horizontalHeader()
            header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
            self.tableView_NhaCungCap.verticalHeader().setDefaultSectionSize(55)
            conn.close()
        except Exception as e:
            print(f"Error loading data: {e}")

    def themNhaCungCap(self):
        try:
            maNCC = int(self.txtMaNCC.text())
            tenNCC = self.txtTenNCC.text()
            diaChi = self.txtDiaChi.text()
            sdt = self.txtSDT.text()
            email = self.txtEmail.text()

            # Kiểm tra dữ liệu đầu vào
            if not self.kiemTraDuLieuNhaCungCap():
                return

            conn = Dataconnection.connectdatabase()
            cursor = conn.cursor()
            cursor.execute("INSERT INTO NhaCungCap (MaNCC, TenNCC, DiaChi, DienThoai, Email) VALUES (%s, %s, %s, %s, %s)",
                           (maNCC, tenNCC, diaChi, sdt, email))
            conn.commit()
            conn.close()

            self.loadTableData()
            self.lamMoi()
            QMessageBox.information(None, "Thông báo", "Thêm nhà cung cấp thành công!")
        except Exception as e:
            QMessageBox.warning(None, "Lỗi", f"Lỗi: {e}")

    def suaNhaCungCap(self):
        try:
            maNCC = int(self.txtMaNCC.text())
            tenNCC = self.txtTenNCC.text()
            diaChi = self.txtDiaChi.text()
            sdt = self.txtSDT.text()
            email = self.txtEmail.text()

            # Kiểm tra dữ liệu đầu vào
            if not self.kiemTraDuLieuNhaCungCap():
                return

            conn = Dataconnection.connectdatabase()
            cursor = conn.cursor()
            cursor.execute("UPDATE NhaCungCap SET TenNCC=%s, DiaChi=%s, DienThoai=%s, Email=%s WHERE MaNCC=%s",
                           (tenNCC, diaChi, sdt, email, maNCC))
            conn.commit()
            conn.close()

            self.loadTableData()
            self.lamMoi()
            QMessageBox.information(None, "Thông báo", "Sửa thông tin nhà cung cấp thành công!")
        except Exception as e:
            QMessageBox.warning(None, "Lỗi", f"Lỗi: {e}")

    def xoaNhaCungCap(self):
        try:
            maNCC = int(self.txtMaNCC.text())

            conn = Dataconnection.connectdatabase()
            cursor = conn.cursor()
            cursor.execute("DELETE FROM NhaCungCap WHERE MaNCC=%s", (maNCC,))
            conn.commit()
            conn.close()

            self.loadTableData()
            self.lamMoi()
            QMessageBox.information(None, "Thông báo", "Xóa nhà cung cấp thành công!")
        except Exception as e:
            QMessageBox.warning(None, "Lỗi", f"Lỗi: {e}")

    def lamMoi(self):
        self.txtMaNCC.clear()
        self.txtTenNCC.clear()
        self.txtDiaChi.clear()
        self.txtSDT.clear()
        self.txtEmail.clear()
        self.loadTableData()

    def timKiemNhaCungCap(self):
        try:
            tenNCC = self.txtTimKiem.text()

            conn = Dataconnection.connectdatabase()
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM NhaCungCap WHERE TenNCC LIKE %s", ('%' + tenNCC + '%',))
            rows = cursor.fetchall()

            self.model.clear()
            self.model.setColumnCount(5)
            self.model.setHorizontalHeaderLabels(["Mã NCC", "Tên NCC", "Địa Chỉ", "Điện Thoại", "Email"])

            for row_number, row_data in enumerate(rows):
                for column_number, data in enumerate(row_data):
                    item = QtGui.QStandardItem(str(data))
                    self.model.setItem(row_number, column_number, item)

            self.tableView_NhaCungCap.setModel(self.model)
            conn.close()
        except Exception as e:
            QMessageBox.warning(None, "Lỗi", f"Lỗi: {e}")

    def kiemTraDuLieuNhaCungCap(self):
        maNCC = self.txtMaNCC.text()
        tenNCC = self.txtTenNCC.text()
        diaChi = self.txtDiaChi.text()
        sdt = self.txtSDT.text()
        email = self.txtEmail.text()

        if not maNCC or not tenNCC or not diaChi or not sdt or not email:
            QMessageBox.warning(None, "Lỗi", "Vui lòng nhập đầy đủ thông tin nhà cung cấp!")
            return False

        # Kiểm tra định dạng email
        if not self.kiemTraEmail(email):
            QMessageBox.warning(None, "Lỗi", "Email không hợp lệ!")
            return False

        # Kiểm tra định dạng số điện thoại
        if not self.kiemTraSoDienThoai(sdt):
            QMessageBox.warning(None, "Lỗi", "Số điện thoại không hợp lệ!")
            return False

        return True

    def kiemTraEmail(self, email):
        import re
        # Kiểm tra định dạng email bằng regular expression
        pattern = r'^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$'
        if re.match(pattern, email):
            return True
        else:
            return False

    def kiemTraSoDienThoai(self, sdt):
        # Kiểm tra số điện thoại chỉ chấp nhận số và độ dài từ 9 đến 15 ký tự
        if sdt.isdigit() and len(sdt) >= 9 and len(sdt) <= 15:
            return True
        else:
            return False
    def rowClicked(self, index):
        # Lấy dữ liệu từ dòng được chọn và hiển thị vào các QLineEdit
        row = index.row()
        if row < 0:
            return
        
        self.txtMaNCC.setText(self.model.index(row, 0).data())
        self.txtTenNCC.setText(self.model.index(row, 1).data())
        self.txtDiaChi.setText(self.model.index(row, 2).data())
        self.txtSDT.setText(self.model.index(row, 3).data())
        self.txtEmail.setText(self.model.index(row, 4).data())
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_NhaCungCap()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())