# Form implementation generated from reading ui file 'ThongKe.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import Dataconnection
from PyQt6.QtGui import QStandardItemModel, QStandardItem
from XuatBaoCao import Print_File
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import  QApplication, QMessageBox, QMainWindow,QPushButton,QWidget, QVBoxLayout
from PyQt6.QtCore import QDate
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import sys
from datetime import datetime
import mplcursors
class MplCanvas(FigureCanvas):

    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)

class Ui_ThongKe(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1563, 871)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(10, 10, 661, 801))
        self.frame1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame1.setObjectName("frame1")
        self.tableView_GiaoDichHoaDon = QtWidgets.QTableView(parent=self.frame1)
        self.tableView_GiaoDichHoaDon.setGeometry(QtCore.QRect(0, 590, 661, 201))
        self.tableView_GiaoDichHoaDon.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.tableView_GiaoDichHoaDon.setObjectName("tableView_GiaoDichHoaDon")
        self.label = QtWidgets.QLabel(parent=self.frame1)
        self.label.setGeometry(QtCore.QRect(240, 430, 191, 41))
        self.label.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame1)
        self.groupBox.setGeometry(QtCore.QRect(0, 490, 661, 91))
        # self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.dateEdit_DenNgay = QtWidgets.QDateEdit(parent=self.groupBox)
        self.dateEdit_DenNgay.setGeometry(QtCore.QRect(310, 40, 126, 22))
        self.dateEdit_DenNgay.setObjectName("dateEdit_DenNgay")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(230, 40, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 55, 16))
        self.label_2.setObjectName("label_2")
        self.dateEdit_TuNgay = QtWidgets.QDateEdit(parent=self.groupBox)
        self.dateEdit_TuNgay.setGeometry(QtCore.QRect(90, 40, 126, 22))
        self.dateEdit_TuNgay.setObjectName("dateEdit_TuNgay")
        self.btnTrasoat = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnTrasoat.setGeometry(QtCore.QRect(450, 40, 111, 24))
        self.btnTrasoat.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnTrasoat.setObjectName("btnTrasoat")
        self.btnPrint = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnPrint.setGeometry(QtCore.QRect(590, 40, 61, 24))
        self.btnPrint.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnPrint.setObjectName("btnPrint")
        self.label_4 = QtWidgets.QLabel(parent=self.frame1)
        self.label_4.setGeometry(QtCore.QRect(260, 10, 131, 41))
        self.label_4.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.frame1)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 60, 661, 121))
        # self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.dateEdit_NgayThangTinhDoanhThu = QtWidgets.QDateEdit(parent=self.groupBox_2)
        self.dateEdit_NgayThangTinhDoanhThu.setGeometry(QtCore.QRect(10, 30, 126, 22))
        self.dateEdit_NgayThangTinhDoanhThu.setObjectName("dateEdit_NgayThangTinhDoanhThu")
        self.radioButton_Thang = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_Thang.setGeometry(QtCore.QRect(170, 30, 91, 20))
        self.radioButton_Thang.setObjectName("radioButton_Thang")
        self.radioButton_Ngay = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_Ngay.setGeometry(QtCore.QRect(250, 30, 91, 20))
        self.radioButton_Ngay.setObjectName("radioButton_Ngay")
        self.btnTinhDoanhThuTheoNT= QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnTinhDoanhThuTheoNT.setGeometry(QtCore.QRect(370, 30, 211, 24))
        self.btnTinhDoanhThuTheoNT.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnTinhDoanhThuTheoNT.setObjectName("btnTinhDoanhThuTheoNT")
        self.txtTinhDoanhThuTheoNT = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.txtTinhDoanhThuTheoNT.setGeometry(QtCore.QRect(250, 80, 113, 22))
        self.txtTinhDoanhThuTheoNT.setObjectName("txtTinhDoanhThuTheoNgayThang")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(150, 80, 91, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(390, 80, 41, 20))
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.frame1)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 190, 661, 80))
        # self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(150, 30, 55, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(150, 30, 91, 20))
        self.label_8.setObjectName("label_8")
        self.txtTinhTongDoanhThu = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.txtTinhTongDoanhThu.setGeometry(QtCore.QRect(250, 30, 113, 22))
        self.txtTinhTongDoanhThu.setObjectName("txtTinhTongDoanhThu")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(390, 30, 41, 20))
        self.label_9.setObjectName("label_9")
        self.btnTongDoanhThuCaNam = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.btnTongDoanhThuCaNam.setGeometry(QtCore.QRect(430, 30, 151, 24))
        self.btnTongDoanhThuCaNam.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnTongDoanhThuCaNam.setObjectName("btnTongDoanhThuCaNam")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.frame1)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 330, 661, 80))
        # self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(150, 30, 55, 16))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(150, 30, 91, 20))
        self.label_14.setObjectName("label_14")
        self.txtTongLuongNhanVien = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.txtTongLuongNhanVien.setGeometry(QtCore.QRect(250, 30, 113, 22))
        self.txtTongLuongNhanVien.setObjectName("txtTongLuongNhanVien")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(390, 30, 41, 20))
        self.label_15.setObjectName("label_15")
        self.btnTongLuongNhanVien = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.btnTongLuongNhanVien.setGeometry(QtCore.QRect(430, 30, 151, 24))
        self.btnTongLuongNhanVien.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnTongLuongNhanVien.setObjectName("btnTongLuongNhanVien")
        self.label_16 = QtWidgets.QLabel(parent=self.frame1)
        self.label_16.setGeometry(QtCore.QRect(230, 280, 191, 41))
        self.label_16.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.frame_2_BieuDo = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2_BieuDo.setGeometry(QtCore.QRect(690, 240, 851, 571))
        self.frame_2_BieuDo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2_BieuDo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2_BieuDo.setObjectName("frame_2_BieuDo")
        self.btnHienTongSanPham = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnHienTongSanPham.setGeometry(QtCore.QRect(720, 60, 121, 51))
        self.btnHienTongSanPham.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnHienTongSanPham.setText("")
        self.btnHienTongSanPham.setObjectName("btnHienTongSanPham")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(720, 30, 131, 20))
        self.label_17.setObjectName("label_17")
        self.btnHienTongNhanVien = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnHienTongNhanVien.setGeometry(QtCore.QRect(1010, 60, 131, 51))
        self.btnHienTongNhanVien.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnHienTongNhanVien.setText("")
        self.btnHienTongNhanVien.setObjectName("btnHienTongNhanVien")
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1010, 30, 131, 20))
        self.label_18.setObjectName("label_18")
        self.btnHienTongNhaCungCap = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnHienTongNhaCungCap.setGeometry(QtCore.QRect(1290, 60, 131, 51))
        self.btnHienTongNhaCungCap.setStyleSheet("background-color: rgb(85, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnHienTongNhaCungCap.setText("")
        self.btnHienTongNhaCungCap.setObjectName("btnHienTongNhaCungCap")
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1280, 30, 151, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(960, 180, 361, 41))
        self.label_20.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1563, 21))
        self.menubar.setObjectName("menubar")
        self.menuManager = QtWidgets.QMenu(parent=self.menubar)
        self.menuManager.setObjectName("menuManager")
        self.menuSetting = QtWidgets.QMenu(parent=self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar) 
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHome = QtGui.QAction(parent=MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionBanHang = QtGui.QAction(parent=MainWindow)
        self.actionBanHang.setObjectName("actionBanHang")
        self.actionNhanVien = QtGui.QAction(parent=MainWindow)
        self.actionNhanVien.setObjectName("actionNhanVien")
        self.actionNhaCungCpa = QtGui.QAction(parent=MainWindow)
        self.actionNhaCungCpa.setObjectName("actionNhaCungCpa")
        self.actionThongKe = QtGui.QAction(parent=MainWindow)
        self.actionThongKe.setObjectName("actionThongKe")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLogout = QtGui.QAction(parent=MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionHoTro = QtGui.QAction(parent=MainWindow)
        self.actionHoTro.setObjectName("actionHoTro")
        self.menuManager.addAction(self.actionHome)
        self.menuManager.addAction(self.actionBanHang)
        self.menuManager.addAction(self.actionNhanVien)
        self.menuManager.addAction(self.actionNhaCungCpa)
        self.menuManager.addAction(self.actionThongKe)
        self.menuSetting.addAction(self.actionExit)
        self.menuSetting.addAction(self.actionLogout)
        self.menuSetting.addAction(self.actionHoTro)
        self.menubar.addAction(self.menuManager.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.giaodich = QStandardItemModel()
        self.tableView_GiaoDichHoaDon.setModel(self.giaodich)
        header = self.tableView_GiaoDichHoaDon.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
       
        self.btnTrasoat.clicked.connect(self.TraSoatLichSu)
        self.btnTongDoanhThuCaNam.clicked.connect(self.Doanh_Thu)
        self.btnTongLuongNhanVien.clicked.connect(self.Luong_NhanVien)
        
        self.dateEdit_TuNgay.setDate(QtCore.QDate.currentDate())
        self.dateEdit_DenNgay.setDate(QtCore.QDate.currentDate())
        self.dateEdit_NgayThangTinhDoanhThu.setDate(QtCore.QDate.currentDate())
        
        self.btnTinhDoanhThuTheoNT.clicked.connect(self.doanhthungaythang)
        # Create a layout for the frame
        layout = QVBoxLayout(self.frame_2_BieuDo)

        # Create a Matplotlib canvas and add it to the layout
        self.canvas = MplCanvas(self.frame_2_BieuDo, width=8, height=6, dpi=80)
        layout.addWidget(self.canvas)

        self.draw_revenue_bar_chart()
        self.btnPrint.clicked.connect(lambda:Print_File(self.tableView_GiaoDichHoaDon,self.txtTinhTongDoanhThu, ["Doanh thu: " + str(self.txtTinhTongDoanhThu.text())+"$", "Lương nhân viên: " + str(self.txtTongLuongNhanVien.text())+"$"]))
        self.LichSu()
        self.calculate_total_employees()
        self.total_NhaCungCap()
        self.total_NongSan()
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LỊCH SỬ GIAO DỊCH"))
        self.groupBox.setTitle(_translate("MainWindow", "Tra soát lịch sử giao dịch < yêu cầu nhập cả 2 >"))
        self.label_3.setText(_translate("MainWindow", "Đến Ngày"))
        self.label_2.setText(_translate("MainWindow", "Từ Ngày"))
        self.btnTrasoat.setText(_translate("MainWindow", "Tra soát lịch sử"))
        self.btnPrint.setText(_translate("MainWindow", "Print "))
        self.label_4.setText(_translate("MainWindow", "DOANH THU"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Nhập Ngày Tháng Và Chọn Tháng Hoặc Ngày Để Tính Doanh Thu"))
        self.radioButton_Thang.setText(_translate("MainWindow", "Tháng"))
        self.radioButton_Ngay.setText(_translate("MainWindow", "Ngày"))
        self.btnTinhDoanhThuTheoNT.setText(_translate("MainWindow", "Doanh Thu Theo (Ngày /Tháng)"))
        self.label_5.setText(_translate("MainWindow", "DOANH THU"))
        self.label_6.setText(_translate("MainWindow", "$"))
        self.groupBox_3.setTitle(_translate("MainWindow", "TỔNG DOANH THU"))
        self.label_8.setText(_translate("MainWindow", "DOANH THU"))
        self.label_9.setText(_translate("MainWindow", "$"))
        self.btnTongDoanhThuCaNam.setText(_translate("MainWindow", "Tính Tổng Doanh Thu"))
        self.groupBox_4.setTitle(_translate("MainWindow", "TỔNG LƯƠNG NHÂN VIÊN"))
        self.label_14.setText(_translate("MainWindow", "Tổng Lương"))
        self.label_15.setText(_translate("MainWindow", "$"))
        self.btnTongLuongNhanVien.setText(_translate("MainWindow", "Tính Lương"))
        self.label_16.setText(_translate("MainWindow", "LƯƠNG NHÂN VIÊN"))
        self.label_17.setText(_translate("MainWindow", "TỔNG SỐ NÔNG SẢN"))
        self.label_18.setText(_translate("MainWindow", "TỔNG SỐ NHÂN VIÊN"))
        self.label_19.setText(_translate("MainWindow", "TỔNG SỐ NHÀ CUNG CẤP"))
        self.label_20.setText(_translate("MainWindow", "BIỂU ĐỒ DOANH THU THEO THÁNG"))
        self.menuManager.setTitle(_translate("MainWindow", "Manager"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionBanHang.setText(_translate("MainWindow", "BanHang"))
        self.actionNhanVien.setText(_translate("MainWindow", "SanPham"))
        self.actionNhaCungCpa.setText(_translate("MainWindow", "NhaCungCap"))
        self.actionThongKe.setText(_translate("MainWindow", "ThongKe"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionHoTro.setText(_translate("MainWindow", "HoTro"))
        
    def doanhthungaythang(self):
    # Kết nối đến cơ sở dữ liệu
        connection = Dataconnection.connectdatabase()
        cursor = connection.cursor()

        # Kiểm tra lựa chọn của người dùng và xây dựng câu truy vấn phù hợp
        if self.radioButton_Thang.isChecked():
            # Trường hợp chọn tháng
            ngay_thang = self.dateEdit_NgayThangTinhDoanhThu.date().toString('yyyy-MM')
            query = """
            SELECT SUM(TongTien) 
            FROM HoaDon 
            WHERE DATE_FORMAT(NgayLap, '%Y-%m') = %s;
            """
            cursor.execute(query, (ngay_thang,))
        elif self.radioButton_Ngay.isChecked():
            # Trường hợp chọn ngày
            ngay_thang = self.dateEdit_NgayThangTinhDoanhThu.date().toString('yyyy-MM-dd')
            query = """
            SELECT SUM(TongTien) 
            FROM HoaDon 
            WHERE DATE(NgayLap) = %s;
            """
            cursor.execute(query, (ngay_thang,))
        else:
            # Trường hợp không chọn gì
            query = """
            SELECT SUM(TongTien) 
            FROM HoaDon;
            """
            cursor.execute(query)
        # Lấy kết quả và hiển thị
        result = cursor.fetchone()

        if result[0] is not None:
            self.txtTinhDoanhThuTheoNT.setText(str(result[0]))
        else:
            self.txtTinhDoanhThuTheoNT.setText('0')

        # Đóng kết nối
        cursor.close()
        connection.close()

    
    def fetch_revenue_data(self):
        # Replace these with your actual database connection details
       
        connection = Dataconnection.connectdatabase()
        cursor = connection.cursor()

        query = """
        SELECT 
            MONTH(NgayLap) as Month, 
            SUM(TongTien) as TotalRevenue 
        FROM HoaDon 
        GROUP BY MONTH(NgayLap)
        ORDER BY MONTH(NgayLap);
        """
        cursor.execute(query)
        result = cursor.fetchall()

        cursor.close()
        connection.close()

        return result

    def draw_revenue_bar_chart(self):
        data = self.fetch_revenue_data()

        # Process the data
        months = [datetime(2000, month, 1).strftime('%B') for month, _ in data]
        total_revenue = [revenue for _, revenue in data]

        self.canvas.axes.clear()
        bars = self.canvas.axes.bar(months, total_revenue)
        self.canvas.axes.set_title('Monthly Total Revenue')
        self.canvas.axes.set_xlabel('Month')
        self.canvas.axes.set_ylabel('Total Revenue')
        self.canvas.draw()

        # Add interactive hover functionality
        cursor = mplcursors.cursor(bars)
        cursor.connect("add", lambda sel: sel.annotation.set_text(f'{sel.target[1]:.2f}'))
        
    
    def calculate_total_employees(self):
        connection = Dataconnection.connectdatabase()
        total_employees = 0
        if connection:
                cursor = connection.cursor()
                cursor.execute("SELECT COUNT(*) FROM NhanVien")
                total_employees = cursor.fetchone()
                tnv = total_employees[0] if total_employees[0] is not None else 0
                connection.close()
                self.btnHienTongNhanVien.setText(f"{tnv}")
                
    def total_NhaCungCap(self):
        connection = Dataconnection.connectdatabase()
        total_ncc = 0
        if connection:
                cursor = connection.cursor()
                cursor.execute("SELECT COUNT(*) FROM NhaCungCap")
                total_ncc = cursor.fetchone()
                tncc = total_ncc[0] if total_ncc[0] is not None else 0
                connection.close()
                self.btnHienTongNhaCungCap.setText(f"{tncc}")
    def total_NongSan(self):
        connection = Dataconnection.connectdatabase()
        total_ns = 0
        if connection:
                cursor = connection.cursor()
                cursor.execute("SELECT COUNT(*) FROM SanPham")
                total_ns = cursor.fetchone()
                tns = total_ns[0] if total_ns[0] is not None else 0
                connection.close()
                self.btnHienTongSanPham.setText(f"{tns}")
                

    # Tiền lương nhân viên
    def Luong_NhanVien(self):
        # Connect to the database and retrieve salary data
        connection = Dataconnection.connectdatabase()
        cursor = connection.cursor()
        cursor.execute("SELECT SUM(Luong) FROM nhanvien")
        result = cursor.fetchone()
        tong_luong = result[0] if result[0] is not None else 0
        connection.close()

        # Update the label with the total salary
        self.txtTongLuongNhanVien.setText(f"{tong_luong:,.0f}")
# Tiền doanh thu
    
    def Doanh_Thu (self):
        # Connect to the database and retrieve salary data
        connection = Dataconnection.connectdatabase()
        cursor = connection.cursor()
        cursor.execute("SELECT SUM(TongTien) FROM hoadon")
        result = cursor.fetchone()
        tong_doanhthu = result[0] if result[0] is not None else 0
        connection.close()

        # Update the label with the total salary
        self.txtTinhTongDoanhThu.setText(f"{tong_doanhthu:,.0f}")


# show lịch sử giao dịch
    def LichSu(self):
        connection = Dataconnection.connectdatabase()
        if connection:
            cursor = connection.cursor()
            cursor.execute("SELECT * FROM HoaDon")
            records = cursor.fetchall()
            if records:
                headers = ['MaHD', 'MaNV', 'NgayLap', 'TongTien']   
                self.giaodich.setHorizontalHeaderLabels(headers)
                for row in records:
                    items = [QtGui.QStandardItem(str(field)) for field in row]
                    self.giaodich.appendRow(items)
            cursor.close()
            Dataconnection.close_connection(connection)
            
    def TraSoatLichSu(self):
        # Lấy ngày bắt đầu và ngày kết thúc từ dateEdit
        tu_ngay = self.dateEdit_TuNgay.date().toPyDate()
        den_ngay = self.dateEdit_DenNgay.date().toPyDate()
        if tu_ngay > den_ngay:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Icon.Warning)
            msg.setText("Ngày bắt đầu phải nhỏ hơn hoặc bằng ngày kết thúc.")
            msg.setWindowTitle("Lỗi")
            msg.exec()
            return
        # Kết nối CSDL và thực hiện truy vấn
        connection = Dataconnection.connectdatabase()
        if connection:
            cursor = connection.cursor()
            # Truy vấn lịch sử giao dịch trong khoảng thời gian từ ngày đến ngày
            cursor.execute("SELECT * FROM HoaDon WHERE NgayLap BETWEEN %s AND %s", (tu_ngay, den_ngay))
            records = cursor.fetchall()
            if records:
                headers = ['MaHD', 'MaNV', 'NgayLap', 'TongTien']
                self.giaodich.clear()  # Xóa dữ liệu cũ trong table view
                self.giaodich.setHorizontalHeaderLabels(headers)
                for row in records:
                    items = [QtGui.QStandardItem(str(field)) for field in row]
                    self.giaodich.appendRow(items)
            cursor.close()
            Dataconnection.close_connection(connection)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ThongKe()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())